/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_management.main;
import project_management.bean.MenuItem;
import project_management.controller.SwitchFrameController;
import project_management.controller.ConnectDBController;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HCMUT
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    ConnectDBController connector;
    public MainFrame() {
        initComponents();
        connector = new ConnectDBController();
        connector.connectDB();
        
        List<MenuItem> menuList = new ArrayList<>();
        menuList.add(new MenuItem("Dashboard", menuItemDashboard));
        menuList.add(new MenuItem("Manage task", menuItemTask));
        menuList.add(new MenuItem("Manage member", menuItemMember));
        menuList.add(new MenuItem("Manage team", menuItemTeam));

        SwitchFrameController controller = new SwitchFrameController(content,titleText);
        controller.setDashboard();
        controller.setEvent(menuList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainView = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menuItemDashboard = new javax.swing.JPanel();
        menuDashboardText = new javax.swing.JLabel();
        menuItemTask = new javax.swing.JPanel();
        menuTaskText = new javax.swing.JLabel();
        projectSystemTitle = new javax.swing.JPanel();
        projectSystemTitleText = new javax.swing.JLabel();
        menuItemMember = new javax.swing.JPanel();
        menuMemberText = new javax.swing.JLabel();
        menuItemTeam = new javax.swing.JPanel();
        menuTeamText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleText.setBackground(new java.awt.Color(221, 221, 221));
        titleText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleText.setForeground(new java.awt.Color(41, 50, 65));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleText.setText("Dashboard");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addComponent(titleText, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addComponent(titleText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainViewLayout = new javax.swing.GroupLayout(mainView);
        mainView.setLayout(mainViewLayout);
        mainViewLayout.setHorizontalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainViewLayout.setVerticalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainViewLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(41, 50, 65));

        menuItemDashboard.setBackground(new java.awt.Color(152, 193, 217));

        menuDashboardText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menuDashboardText.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboardText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboardText.setText("My dashboard");

        javax.swing.GroupLayout menuItemDashboardLayout = new javax.swing.GroupLayout(menuItemDashboard);
        menuItemDashboard.setLayout(menuItemDashboardLayout);
        menuItemDashboardLayout.setHorizontalGroup(
            menuItemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDashboardText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuItemDashboardLayout.setVerticalGroup(
            menuItemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemDashboardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(menuDashboardText)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menuItemTask.setBackground(new java.awt.Color(152, 193, 217));

        menuTaskText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menuTaskText.setForeground(new java.awt.Color(255, 255, 255));
        menuTaskText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTaskText.setText("Manage task");

        javax.swing.GroupLayout menuItemTaskLayout = new javax.swing.GroupLayout(menuItemTask);
        menuItemTask.setLayout(menuItemTaskLayout);
        menuItemTaskLayout.setHorizontalGroup(
            menuItemTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTaskText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuItemTaskLayout.setVerticalGroup(
            menuItemTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemTaskLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(menuTaskText)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        projectSystemTitle.setBackground(new java.awt.Color(238, 108, 77));

        projectSystemTitleText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        projectSystemTitleText.setForeground(new java.awt.Color(255, 255, 255));
        projectSystemTitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectSystemTitleText.setText("PROJECT MANAGEMENT");

        javax.swing.GroupLayout projectSystemTitleLayout = new javax.swing.GroupLayout(projectSystemTitle);
        projectSystemTitle.setLayout(projectSystemTitleLayout);
        projectSystemTitleLayout.setHorizontalGroup(
            projectSystemTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(projectSystemTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(projectSystemTitleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );
        projectSystemTitleLayout.setVerticalGroup(
            projectSystemTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
            .addGroup(projectSystemTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(projectSystemTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        menuItemMember.setBackground(new java.awt.Color(152, 193, 217));

        menuMemberText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menuMemberText.setForeground(new java.awt.Color(255, 255, 255));
        menuMemberText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuMemberText.setText("Manage member");

        javax.swing.GroupLayout menuItemMemberLayout = new javax.swing.GroupLayout(menuItemMember);
        menuItemMember.setLayout(menuItemMemberLayout);
        menuItemMemberLayout.setHorizontalGroup(
            menuItemMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMemberText, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        menuItemMemberLayout.setVerticalGroup(
            menuItemMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemMemberLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(menuMemberText)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menuItemTeam.setBackground(new java.awt.Color(152, 193, 217));

        menuTeamText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menuTeamText.setForeground(new java.awt.Color(255, 255, 255));
        menuTeamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTeamText.setText("Manage team");

        javax.swing.GroupLayout menuItemTeamLayout = new javax.swing.GroupLayout(menuItemTeam);
        menuItemTeam.setLayout(menuItemTeamLayout);
        menuItemTeamLayout.setHorizontalGroup(
            menuItemTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTeamText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        menuItemTeamLayout.setVerticalGroup(
            menuItemTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItemTeamLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(menuTeamText)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectSystemTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuItemTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(menuItemMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuItemTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuItemDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(projectSystemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(menuItemDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItemTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItemMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItemTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(mainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JPanel mainView;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuDashboardText;
    private javax.swing.JPanel menuItemDashboard;
    private javax.swing.JPanel menuItemMember;
    private javax.swing.JPanel menuItemTask;
    private javax.swing.JPanel menuItemTeam;
    private javax.swing.JLabel menuMemberText;
    private javax.swing.JLabel menuTaskText;
    private javax.swing.JLabel menuTeamText;
    private javax.swing.JPanel projectSystemTitle;
    private javax.swing.JLabel projectSystemTitleText;
    private javax.swing.JPanel title;
    public javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
