/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_management.view.TeamManagement;
import project_management.model.Team;
import project_management.controller.TeamController.TeamController;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author HCMUT
 */

public class TeamManagement extends javax.swing.JPanel {
    private TeamController controller = new TeamController();
    
    private ArrayList<Team> list;
    int selectedIndex;
    public ArrayList<Team> foundlist;
    DefaultTableModel modelf;
    DefaultTableModel model;
    /**
     * Creates new form TeamManagement
     */
    public TeamManagement() {
        initComponents();
        list= controller.getAllTeams();
        foundlist=new ArrayList<>();
        model = (DefaultTableModel) tblTeam.getModel();
        modelf = (DefaultTableModel) foundTable.getModel();
        for (int i = 0; i < list.size(); ++i) {
            model.addRow(new Object[]{
                list.get(i).getId(), list.get(i).getName(), list.get(i).getDescription(), list.get(i).getLeader_id()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfAddTeam = new javax.swing.JFrame();
        btnAdd_AddTeam = new javax.swing.JButton();
        btnCancel_AddTeam = new javax.swing.JButton();
        lbName_AddTeam = new javax.swing.JLabel();
        lbDescription_AddTeam = new javax.swing.JLabel();
        lbLeader_AddTeam = new javax.swing.JLabel();
        txfName_AddTeam = new javax.swing.JTextField();
        txfDescription_AddTeam = new javax.swing.JTextField();
        txfLeader_AddTeam = new javax.swing.JTextField();
        jfEditTeam = new javax.swing.JFrame();
        btnSave_EditTeam = new javax.swing.JButton();
        btnCancel_EditTeam = new javax.swing.JButton();
        lbName_EditTeam = new javax.swing.JLabel();
        lbDescription_EditTeam = new javax.swing.JLabel();
        lbLeader_EditTeam = new javax.swing.JLabel();
        txfName_EditTeam = new javax.swing.JTextField();
        txfDescription_EditTeam = new javax.swing.JTextField();
        txfLeader_EditTeam = new javax.swing.JTextField();
        jfSearchTeam = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        foundTable = new javax.swing.JTable();
        jpnTeam = new javax.swing.JPanel();
        btnAddTeam = new javax.swing.JButton();
        btnDeleteTeam = new javax.swing.JButton();
        btnEditTeam = new javax.swing.JButton();
        btnSearchTeam = new javax.swing.JButton();
        srpTeam = new javax.swing.JScrollPane();
        tblTeam = new javax.swing.JTable();
        jpnTeamTitle = new javax.swing.JPanel();
        lbTeamTitle = new javax.swing.JLabel();

        jfAddTeam.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfAddTeam.setTitle("Add");
        jfAddTeam.setLocation(new java.awt.Point(500, 200));
        jfAddTeam.setSize(new java.awt.Dimension(400, 350));

        btnAdd_AddTeam.setBackground(new java.awt.Color(0, 153, 254));
        btnAdd_AddTeam.setText("Add");
        btnAdd_AddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_AddTeamActionPerformed(evt);
            }
        });

        btnCancel_AddTeam.setBackground(new java.awt.Color(0, 153, 254));
        btnCancel_AddTeam.setText("Cancel");
        btnCancel_AddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_AddTeamActionPerformed(evt);
            }
        });

        lbName_AddTeam.setText("Name");

        lbDescription_AddTeam.setText("Description");

        lbLeader_AddTeam.setText("Leader");

        txfName_AddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName_AddTeamActionPerformed(evt);
            }
        });

        txfLeader_AddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLeader_AddTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfAddTeamLayout = new javax.swing.GroupLayout(jfAddTeam.getContentPane());
        jfAddTeam.getContentPane().setLayout(jfAddTeamLayout);
        jfAddTeamLayout.setHorizontalGroup(
            jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfAddTeamLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfAddTeamLayout.createSequentialGroup()
                        .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jfAddTeamLayout.createSequentialGroup()
                                .addComponent(lbLeader_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(txfLeader_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jfAddTeamLayout.createSequentialGroup()
                                    .addComponent(lbName_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(txfName_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfAddTeamLayout.createSequentialGroup()
                                    .addComponent(lbDescription_AddTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfDescription_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(jfAddTeamLayout.createSequentialGroup()
                        .addComponent(btnAdd_AddTeam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel_AddTeam)
                        .addGap(74, 74, 74))))
        );
        jfAddTeamLayout.setVerticalGroup(
            jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfAddTeamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName_AddTeam)
                    .addComponent(txfName_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescription_AddTeam)
                    .addComponent(txfDescription_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLeader_AddTeam)
                    .addComponent(txfLeader_AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jfAddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_AddTeam)
                    .addComponent(btnCancel_AddTeam))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jfEditTeam.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfEditTeam.setTitle("Edit Information");
        jfEditTeam.setLocation(new java.awt.Point(500, 200));
        jfEditTeam.setSize(new java.awt.Dimension(400, 350));

        btnSave_EditTeam.setBackground(new java.awt.Color(0, 153, 254));
        btnSave_EditTeam.setText("Save");
        btnSave_EditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_EditTeamActionPerformed(evt);
            }
        });

        btnCancel_EditTeam.setBackground(new java.awt.Color(0, 153, 254));
        btnCancel_EditTeam.setText("Cancel");
        btnCancel_EditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_EditTeamActionPerformed(evt);
            }
        });

        lbName_EditTeam.setText("Name");

        lbDescription_EditTeam.setText("Description");

        lbLeader_EditTeam.setText("Leader");

        txfName_EditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName_EditTeamActionPerformed(evt);
            }
        });

        txfLeader_EditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLeader_EditTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfEditTeamLayout = new javax.swing.GroupLayout(jfEditTeam.getContentPane());
        jfEditTeam.getContentPane().setLayout(jfEditTeamLayout);
        jfEditTeamLayout.setHorizontalGroup(
            jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfEditTeamLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfEditTeamLayout.createSequentialGroup()
                        .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jfEditTeamLayout.createSequentialGroup()
                                .addComponent(lbLeader_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(txfLeader_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jfEditTeamLayout.createSequentialGroup()
                                    .addComponent(lbName_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(txfName_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfEditTeamLayout.createSequentialGroup()
                                    .addComponent(lbDescription_EditTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfDescription_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(jfEditTeamLayout.createSequentialGroup()
                        .addComponent(btnSave_EditTeam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel_EditTeam)
                        .addGap(74, 74, 74))))
        );
        jfEditTeamLayout.setVerticalGroup(
            jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfEditTeamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName_EditTeam)
                    .addComponent(txfName_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescription_EditTeam)
                    .addComponent(txfDescription_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLeader_EditTeam)
                    .addComponent(txfLeader_EditTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jfEditTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave_EditTeam)
                    .addComponent(btnCancel_EditTeam))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jfSearchTeam.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfSearchTeam.setTitle("Search");
        jfSearchTeam.setLocation(new java.awt.Point(500, 200));
        jfSearchTeam.setSize(new java.awt.Dimension(800, 600));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Search By");

        jLabel10.setText("Name");

        jLabel11.setText("Team");

        jLabel12.setText("Description");

        jLabel13.setText("Leader");

        jButton6.setBackground(new java.awt.Color(0, 153, 254));
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setText("Search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        foundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Leader"
            }
        ));
        jScrollPane2.setViewportView(foundTable);

        javax.swing.GroupLayout jfSearchTeamLayout = new javax.swing.GroupLayout(jfSearchTeam.getContentPane());
        jfSearchTeam.getContentPane().setLayout(jfSearchTeamLayout);
        jfSearchTeamLayout.setHorizontalGroup(
            jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchTeamLayout.createSequentialGroup()
                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jfSearchTeamLayout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfSearchTeamLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jfSearchTeamLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton6)))
                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSearchTeamLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jfSearchTeamLayout.createSequentialGroup()
                                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField12))
                                .addGap(50, 50, 50)
                                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jButton9)
                                    .addComponent(jButton11)
                                    .addComponent(jButton12))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jfSearchTeamLayout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
            .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfSearchTeamLayout.createSequentialGroup()
                    .addContainerGap(685, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addGap(16, 16, 16)))
        );
        jfSearchTeamLayout.setVerticalGroup(
            jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchTeamLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSearchTeamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(214, 214, 214))
                    .addGroup(jfSearchTeamLayout.createSequentialGroup()
                        .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jfSearchTeamLayout.createSequentialGroup()
                                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(jfSearchTeamLayout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)
                                .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jButton7))))
                        .addGap(22, 22, 22)
                        .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11))
                        .addGap(27, 27, 27)
                        .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(67, Short.MAX_VALUE))))
            .addGroup(jfSearchTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jfSearchTeamLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        jpnTeam.setBackground(new java.awt.Color(238, 238, 238));

        btnAddTeam.setBackground(new java.awt.Color(61, 90, 128));
        btnAddTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/group_add_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnAddTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTeamMouseClicked(evt);
            }
        });
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeamActionPerformed(evt);
            }
        });

        btnDeleteTeam.setBackground(new java.awt.Color(61, 90, 128));
        btnDeleteTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/group_remove_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeamActionPerformed(evt);
            }
        });

        btnEditTeam.setBackground(new java.awt.Color(61, 90, 128));
        btnEditTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/edit_note_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnEditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTeamActionPerformed(evt);
            }
        });

        btnSearchTeam.setBackground(new java.awt.Color(60, 91, 128));
        btnSearchTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/quick_reference_all_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnSearchTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchTeamMouseClicked(evt);
            }
        });
        btnSearchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTeamActionPerformed(evt);
            }
        });

        tblTeam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        tblTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Leader"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTeam.setGridColor(new java.awt.Color(61, 90, 128));
        tblTeam.setRowHeight(25);
        tblTeam.setShowGrid(true);
        tblTeam.getTableHeader().setReorderingAllowed(false);
        srpTeam.setViewportView(tblTeam);
        if (tblTeam.getColumnModel().getColumnCount() > 0) {
            tblTeam.getColumnModel().getColumn(0).setResizable(false);
            tblTeam.getColumnModel().getColumn(1).setResizable(false);
            tblTeam.getColumnModel().getColumn(2).setResizable(false);
            tblTeam.getColumnModel().getColumn(3).setResizable(false);
        }

        jpnTeamTitle.setBackground(new java.awt.Color(61, 90, 128));
        jpnTeamTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 50, 65), 4));

        lbTeamTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTeamTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTeamTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTeamTitle.setText("Team list");

        javax.swing.GroupLayout jpnTeamTitleLayout = new javax.swing.GroupLayout(jpnTeamTitle);
        jpnTeamTitle.setLayout(jpnTeamTitleLayout);
        jpnTeamTitleLayout.setHorizontalGroup(
            jpnTeamTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnTeamTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbTeamTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
        );
        jpnTeamTitleLayout.setVerticalGroup(
            jpnTeamTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jpnTeamTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTeamTitleLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTeamTitle)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpnTeamLayout = new javax.swing.GroupLayout(jpnTeam);
        jpnTeam.setLayout(jpnTeamLayout);
        jpnTeamLayout.setHorizontalGroup(
            jpnTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTeamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTeam)
                .addGap(80, 80, 80)
                .addComponent(btnDeleteTeam)
                .addGap(80, 80, 80)
                .addComponent(btnEditTeam)
                .addGap(80, 80, 80)
                .addComponent(btnSearchTeam)
                .addGap(178, 178, 178))
            .addGroup(jpnTeamLayout.createSequentialGroup()
                .addGroup(jpnTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(srpTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addComponent(jpnTeamTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnTeamLayout.setVerticalGroup(
            jpnTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTeamLayout.createSequentialGroup()
                .addComponent(jpnTeamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(srpTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jpnTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddTeam)
                        .addComponent(btnDeleteTeam)
                        .addComponent(btnEditTeam))
                    .addComponent(btnSearchTeam))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_AddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_AddTeamActionPerformed
        Team t = new Team();

        t.setName(txfName_AddTeam.getText());
        t.setDescription(txfDescription_AddTeam.getText());
        t.setLeader_id(Integer.parseInt(txfLeader_AddTeam.getText()));
         // TODO add your handling code here:
        int n = controller.appendTeam(t);
        
        jfAddTeam.setVisible(false);
        txfName_AddTeam.setText("");
        txfDescription_AddTeam.setText("");
        txfLeader_AddTeam.setText("");
        
        model.addRow(new Object[]{
            n, t.getName(), t.getDescription(), t.getLeader_id()
        });
        
        
    }//GEN-LAST:event_btnAdd_AddTeamActionPerformed

    /*public void showResult() {
        
    } */
    private void btnAddTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTeamMouseClicked
        // TODO add your handling code here:
        jfAddTeam.setVisible(true);
    }//GEN-LAST:event_btnAddTeamMouseClicked

    private void txfLeader_AddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLeader_AddTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLeader_AddTeamActionPerformed

    private void txfName_AddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName_AddTeamActionPerformed
        if(!txfName_AddTeam.getText().equals("")){
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName_AddTeamActionPerformed

    private void btnAddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTeamActionPerformed

    private void btnCancel_AddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_AddTeamActionPerformed
        txfName_AddTeam.setText("");
        txfDescription_AddTeam.setText("");
        txfLeader_AddTeam.setText("");
        jfAddTeam.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel_AddTeamActionPerformed

    private void btnEditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTeamActionPerformed
        selectedIndex = tblTeam.getSelectedRow();
        int edit_id = 0;
        if (controller.isEmpty()){
            JOptionPane.showMessageDialog(btnAdd_AddTeam, "There is nothing to edit");
        }
        else if (selectedIndex == -1){
            JOptionPane.showMessageDialog(btnAdd_AddTeam, "Select row to edit");
        }
        else {
            edit_id = (int) tblTeam.getModel().getValueAt(selectedIndex,0);
            Team t = controller.getTeamById(edit_id);
            txfName_EditTeam.setText(t.getName());    
            txfDescription_EditTeam.setText(t.getDescription());   
            txfLeader_EditTeam.setText(Integer.toString(t.getLeader_id()));  
            jfEditTeam.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditTeamActionPerformed

    private void btnDeleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeamActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTeam.getSelectedRow();
        int remove_id = (int) tblTeam.getModel().getValueAt(selectedRow,0);
        if(selectedRow == -1) JOptionPane.showMessageDialog(btnAdd_AddTeam, "Please select row to delete");
        // Nếu có hàng được chọn, hiển thị hộp thoại xác nhận trước khi xóa hàng
        if (selectedRow != -1) {
            int confirmed = JOptionPane.showConfirmDialog(null, 
                "Are you sure you want to delete this row?", 
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                model.removeRow(selectedRow);
                controller.removeTeamById(remove_id);
            }
        }    
    }//GEN-LAST:event_btnDeleteTeamActionPerformed

    private void btnSave_EditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_EditTeamActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
                    "Are you sure you want to edit this row?", 
                    "Confirm Edit", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION){
            Team t = new Team();
            int edit_id = (int) tblTeam.getModel().getValueAt(selectedIndex,0);
            t.setId(edit_id);
            t.setName(txfName_EditTeam.getText());
            t.setDescription(txfDescription_EditTeam.getText());
            t.setLeader_id(Integer.parseInt(txfLeader_EditTeam.getText()));    
            
            txfName_EditTeam.setText("");
            txfDescription_EditTeam.setText("");
            txfLeader_EditTeam.setText("");
            jfEditTeam.setVisible(false);
            model.setValueAt((Object)edit_id,selectedIndex,0);
            model.setValueAt(t.getName(),selectedIndex,1);
            model.setValueAt(t.getDescription(),selectedIndex,2);
            model.setValueAt(t.getLeader_id(),selectedIndex,3);
            
            controller.editTeam(t);
        }
    }//GEN-LAST:event_btnSave_EditTeamActionPerformed
    private void btnCancel_EditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_EditTeamActionPerformed
      txfName_EditTeam.setText("");
      txfDescription_EditTeam.setText("");
      txfLeader_EditTeam.setText("");
        jfEditTeam.setVisible(false);       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel_EditTeamActionPerformed

    private void txfName_EditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName_EditTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName_EditTeamActionPerformed

    private void txfLeader_EditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLeader_EditTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLeader_EditTeamActionPerformed

    private void btnSearchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTeamActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchTeamActionPerformed

    private void btnSearchTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchTeamMouseClicked
        jfSearchTeam.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchTeamMouseClicked

    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        modelf.setRowCount(0);
        int t= Integer.parseInt(jTextField12.getText());
        for (int i=0;i<list.size();i++){
            Team m=list.get(i);
            if (m.getLeader_id() == t) foundlist.add(m);
        }
     
        if(foundlist==null) JOptionPane.showMessageDialog(btnAdd_AddTeam,"Can't find");
        else {
            for (int i=0;i<foundlist.size();i++){
            modelf.addRow(new Object[]{
                foundlist.get(i).getId(), foundlist.get(i).getName(), foundlist.get(i).getDescription(), foundlist.get(i).getLeader_id()
            });
        }
    }
        while(foundlist.isEmpty()) foundlist.remove(0);
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
modelf.setRowCount(0);
        String t= jTextField11.getText();
        for (int i=0;i<list.size();i++){
            Team m=list.get(i);
            if (m.getDescription().equalsIgnoreCase(t)) foundlist.add(m);
        }
        if(foundlist==null) JOptionPane.showMessageDialog(btnAdd_AddTeam,"Can't find");
 else {
     for (int i=0;i<foundlist.size();i++){
          modelf.addRow(new Object[]{
   foundlist.get(i).getId(), foundlist.get(i).getName(), foundlist.get(i).getDescription(), foundlist.get(i).getLeader_id()
    });
     }
 }
       while(foundlist.isEmpty()) foundlist.remove(0);    
       jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
     
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 modelf.setRowCount(0);
        String t= jTextField9.getText();
        for (int i=0;i<list.size();i++){
            Team m=list.get(i);
            if (m.getName().equalsIgnoreCase(t)) foundlist.add(m);
        }
    
        if(foundlist==null) JOptionPane.showMessageDialog(btnAdd_AddTeam,"Can't find");
 else {
     for (int i=0;i<foundlist.size();i++){
          modelf.addRow(new Object[]{   
   foundlist.get(i).getId(), foundlist.get(i).getName(), foundlist.get(i).getDescription(), foundlist.get(i).getLeader_id()
    });
     }
 }
       while(foundlist.isEmpty()) foundlist.remove(0);
       jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
     
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
modelf.setRowCount(0);
        int t= Integer.parseInt(jTextField10.getText());
        for (int i=0;i<list.size();i++){
            Team m=list.get(i);
            if (m.getId() == t) foundlist.add(m);
        }
        if(foundlist==null) JOptionPane.showMessageDialog(btnAdd_AddTeam,"Can't find");
 else {
     for (int i=0;i<foundlist.size();i++){
          modelf.addRow(new Object[]{
   foundlist.get(i).getId(), foundlist.get(i).getName(), foundlist.get(i).getDescription(), foundlist.get(i).getLeader_id()
    });
     }
    
 }
       while(foundlist.isEmpty()) foundlist.remove(0);
       jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
     
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
modelf.setRowCount(0);
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jfSearchTeam.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JButton btnAdd_AddTeam;
    private javax.swing.JButton btnCancel_AddTeam;
    private javax.swing.JButton btnCancel_EditTeam;
    private javax.swing.JButton btnDeleteTeam;
    private javax.swing.JButton btnEditTeam;
    private javax.swing.JButton btnSave_EditTeam;
    private javax.swing.JButton btnSearchTeam;
    private javax.swing.JTable foundTable;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JFrame jfAddTeam;
    private javax.swing.JFrame jfEditTeam;
    private javax.swing.JFrame jfSearchTeam;
    private javax.swing.JPanel jpnTeam;
    private javax.swing.JPanel jpnTeamTitle;
    private javax.swing.JLabel lbDescription_AddTeam;
    private javax.swing.JLabel lbDescription_EditTeam;
    private javax.swing.JLabel lbLeader_AddTeam;
    private javax.swing.JLabel lbLeader_EditTeam;
    private javax.swing.JLabel lbName_AddTeam;
    private javax.swing.JLabel lbName_EditTeam;
    private javax.swing.JLabel lbTeamTitle;
    private javax.swing.JScrollPane srpTeam;
    private javax.swing.JTable tblTeam;
    private javax.swing.JTextField txfDescription_AddTeam;
    private javax.swing.JTextField txfDescription_EditTeam;
    private javax.swing.JTextField txfLeader_AddTeam;
    private javax.swing.JTextField txfLeader_EditTeam;
    private javax.swing.JTextField txfName_AddTeam;
    private javax.swing.JTextField txfName_EditTeam;
    // End of variables declaration//GEN-END:variables
}
