/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_management.view.MemberManagement;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import project_management.model.Member;
import project_management.controller.MemberController.MemberController;

/**
 *
 * @author HCMUT
 */
import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HCMUT
 */
public class MemberManagement extends javax.swing.JPanel {

    /**
     * Creates new form MemberManagement
     */
    private MemberController controller = new MemberController();
    
    MemberList memberList = new MemberList();
    //private searchResult search;
    List<Member> memberListTemp = null;
    private ArrayList<Member> list;
    int selectedIndex;
    public ArrayList<Member> foundlist;
    DefaultTableModel modelf;
    DefaultTableModel model;
    
    public MemberManagement() {
        initComponents();
        list= controller.getAllMembers();
        foundlist=new ArrayList<>();
        model = (DefaultTableModel) tblMember.getModel();
        //modelf = (DefaultTableModel) foundTable.getModel();
        for (int i = 0; i < list.size(); ++i) {
            model.addRow(new Object[]{
                list.get(i).getId(), list.get(i).getName(), list.get(i).getPersonal_id(), list.get(i).getPosition(), list.get(i).getTeam_id()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfAddMember = new javax.swing.JFrame();
        lbName_AddMember = new javax.swing.JLabel();
        lbPersonalId_AddMember = new javax.swing.JLabel();
        lbTeam_AddMember = new javax.swing.JLabel();
        lbPosition_AddMember = new javax.swing.JLabel();
        lbEmail_AddMember = new javax.swing.JLabel();
        lbDateOfBirth_AddMember = new javax.swing.JLabel();
        lbGender_AddMember = new javax.swing.JLabel();
        lbMajor_AddMember = new javax.swing.JLabel();
        txfName_AddMember = new javax.swing.JTextField();
        txfPersonalId_AddMember = new javax.swing.JTextField();
        txfEmail_AddMember = new javax.swing.JTextField();
        txfMajor_AddMember = new javax.swing.JTextField();
        btnAdd_AddMember = new javax.swing.JButton();
        btnCancel_AddMember = new javax.swing.JButton();
        cbTeam_AddMember = new javax.swing.JComboBox<>();
        dcDateOfBirth_AddMember = new com.toedter.calendar.JDateChooser();
        btnNewTeam_AddMember = new javax.swing.JButton();
        cbGender_AddMember = new javax.swing.JComboBox<>();
        cbPosition_AddMember = new javax.swing.JComboBox<>();
        jfEditMember = new javax.swing.JFrame();
        closeEdit = new javax.swing.JButton();
        txfName_EditMember = new javax.swing.JTextField();
        lbName_EditMember = new javax.swing.JLabel();
        lbDateOfBirth_EditMember = new javax.swing.JLabel();
        lbTeam_EditMember = new javax.swing.JLabel();
        txfMajor_EditMember = new javax.swing.JTextField();
        txfPersonalId_EditMember = new javax.swing.JTextField();
        cbPosition_EditMember = new javax.swing.JComboBox<>();
        cbTeam_EditMember = new javax.swing.JComboBox<>();
        lbMajor_EditMember = new javax.swing.JLabel();
        lbPosition_EditMember = new javax.swing.JLabel();
        txfEmail_EditMember = new javax.swing.JTextField();
        btnNewTeam_EditMember = new javax.swing.JButton();
        dcDateOfBirth_EditMember = new com.toedter.calendar.JDateChooser();
        lbPersonalId_EditMember = new javax.swing.JLabel();
        cbGender_EditMember = new javax.swing.JComboBox<>();
        lbEmail_EditMember = new javax.swing.JLabel();
        lbGender_EditMember = new javax.swing.JLabel();
        btnUpdate_EditMember = new javax.swing.JButton();
        jfRemoveMember = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        removeID = new javax.swing.JTextField();
        removeName = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        closeRemove = new javax.swing.JButton();
        jfRemoveSelectedMember = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        sure = new javax.swing.JButton();
        notsure = new javax.swing.JButton();
        another = new javax.swing.JButton();
        jfSearchMember = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        searchID = new javax.swing.JTextField();
        searchPos = new javax.swing.JTextField();
        searchTeam = new javax.swing.JTextField();
        findbtn = new javax.swing.JButton();
        closeSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jfSearchResult = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jpnMember = new javax.swing.JPanel();
        btnAddMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        btnEditMember = new javax.swing.JButton();
        jpnMemberTitle = new javax.swing.JPanel();
        lbMemberTitle = new javax.swing.JLabel();
        btnFilterMember = new javax.swing.JButton();
        srpMember = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnDetailsMember = new javax.swing.JButton();

        jfAddMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfAddMember.setTitle("Add Member");
        jfAddMember.setBackground(new java.awt.Color(12, 210, 229));
        jfAddMember.setLocation(new java.awt.Point(500, 200));

        lbName_AddMember.setText("Name (*):");

        lbPersonalId_AddMember.setText("Personal ID (*):");

        lbTeam_AddMember.setText("Team (*):");

        lbPosition_AddMember.setText("Position (*):");

        lbEmail_AddMember.setText("Email:");

        lbDateOfBirth_AddMember.setText("Date of Birth:");

        lbGender_AddMember.setText("Gender:");

        lbMajor_AddMember.setText("Major:");

        txfName_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName_AddMemberActionPerformed(evt);
            }
        });

        txfPersonalId_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPersonalId_AddMemberActionPerformed(evt);
            }
        });

        btnAdd_AddMember.setBackground(new java.awt.Color(0, 153, 204));
        btnAdd_AddMember.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd_AddMember.setText("ADD");
        btnAdd_AddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd_AddMemberMouseClicked(evt);
            }
        });

        btnCancel_AddMember.setBackground(new java.awt.Color(0, 153, 204));
        btnCancel_AddMember.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel_AddMember.setText("Cancel");
        btnCancel_AddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancel_AddMemberMouseClicked(evt);
            }
        });
        btnCancel_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_AddMemberActionPerformed(evt);
            }
        });

        cbTeam_AddMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        btnNewTeam_AddMember.setBackground(new java.awt.Color(204, 204, 204));
        btnNewTeam_AddMember.setText("New");
        btnNewTeam_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTeam_AddMemberActionPerformed(evt);
            }
        });

        cbGender_AddMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        cbPosition_AddMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Leader" }));
        cbPosition_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPosition_AddMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfAddMemberLayout = new javax.swing.GroupLayout(jfAddMember.getContentPane());
        jfAddMember.getContentPane().setLayout(jfAddMemberLayout);
        jfAddMemberLayout.setHorizontalGroup(
            jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfAddMemberLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEmail_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPosition_AddMember)
                    .addComponent(lbName_AddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTeam_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfAddMemberLayout.createSequentialGroup()
                            .addComponent(cbTeam_AddMember, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNewTeam_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txfName_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txfEmail_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPosition_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jfAddMemberLayout.createSequentialGroup()
                        .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPersonalId_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDateOfBirth_AddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDateOfBirth_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPersonalId_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jfAddMemberLayout.createSequentialGroup()
                        .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGender_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMajor_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGender_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMajor_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(jfAddMemberLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnAdd_AddMember)
                .addGap(110, 110, 110)
                .addComponent(btnCancel_AddMember)
                .addGap(0, 148, Short.MAX_VALUE))
        );
        jfAddMemberLayout.setVerticalGroup(
            jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfAddMemberLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName_AddMember)
                    .addComponent(txfName_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPersonalId_AddMember)
                    .addComponent(txfPersonalId_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTeam_AddMember)
                    .addComponent(lbDateOfBirth_AddMember)
                    .addComponent(dcDateOfBirth_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewTeam_AddMember)
                        .addComponent(lbTeam_AddMember)))
                .addGap(18, 18, 18)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPosition_AddMember)
                    .addComponent(lbGender_AddMember)
                    .addComponent(cbGender_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPosition_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmail_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail_AddMember)
                    .addComponent(lbMajor_AddMember)
                    .addComponent(txfMajor_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jfAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_AddMember)
                    .addComponent(btnCancel_AddMember))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jfEditMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfEditMember.setTitle("Update Member Info");
        jfEditMember.setLocation(new java.awt.Point(500, 300));
        jfEditMember.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jfEditMemberformWindowOpened(evt);
            }
        });

        closeEdit.setBackground(new java.awt.Color(0, 153, 204));
        closeEdit.setForeground(new java.awt.Color(255, 255, 255));
        closeEdit.setText("Cancel");
        closeEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeEditMouseClicked(evt);
            }
        });
        closeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeEditActionPerformed(evt);
            }
        });

        txfName_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName_EditMemberActionPerformed(evt);
            }
        });

        lbName_EditMember.setText("Name (*):");

        lbDateOfBirth_EditMember.setText("Date of Birth:");

        lbTeam_EditMember.setText("Team (*):");

        txfPersonalId_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPersonalId_EditMemberActionPerformed(evt);
            }
        });

        cbPosition_EditMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Leader" }));
        cbPosition_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPosition_EditMemberActionPerformed(evt);
            }
        });

        cbTeam_EditMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        lbMajor_EditMember.setText("Major:");

        lbPosition_EditMember.setText("Position (*):");

        btnNewTeam_EditMember.setBackground(new java.awt.Color(204, 204, 204));
        btnNewTeam_EditMember.setText("New");
        btnNewTeam_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTeam_EditMemberActionPerformed(evt);
            }
        });

        lbPersonalId_EditMember.setText("Personal ID (*):");

        cbGender_EditMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        lbEmail_EditMember.setText("Email:");

        lbGender_EditMember.setText("Gender:");

        btnUpdate_EditMember.setBackground(new java.awt.Color(0, 153, 204));
        btnUpdate_EditMember.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate_EditMember.setText("Update");
        btnUpdate_EditMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate_EditMemberMouseClicked(evt);
            }
        });
        btnUpdate_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_EditMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfEditMemberLayout = new javax.swing.GroupLayout(jfEditMember.getContentPane());
        jfEditMember.getContentPane().setLayout(jfEditMemberLayout);
        jfEditMemberLayout.setHorizontalGroup(
            jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfEditMemberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate_EditMember)
                .addGap(127, 127, 127)
                .addComponent(closeEdit)
                .addGap(104, 104, 104))
            .addGroup(jfEditMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEmail_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPosition_EditMember)
                    .addComponent(lbName_EditMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTeam_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfEditMemberLayout.createSequentialGroup()
                            .addComponent(cbTeam_EditMember, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNewTeam_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txfName_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txfEmail_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPosition_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jfEditMemberLayout.createSequentialGroup()
                        .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPersonalId_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDateOfBirth_EditMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDateOfBirth_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPersonalId_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jfEditMemberLayout.createSequentialGroup()
                        .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGender_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMajor_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGender_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMajor_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jfEditMemberLayout.setVerticalGroup(
            jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfEditMemberLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName_EditMember)
                    .addComponent(txfName_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPersonalId_EditMember)
                    .addComponent(txfPersonalId_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTeam_EditMember)
                    .addComponent(lbDateOfBirth_EditMember)
                    .addComponent(dcDateOfBirth_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewTeam_EditMember)
                        .addComponent(lbTeam_EditMember)))
                .addGap(18, 18, 18)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPosition_EditMember)
                    .addComponent(lbGender_EditMember)
                    .addComponent(cbGender_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPosition_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmail_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail_EditMember)
                    .addComponent(lbMajor_EditMember)
                    .addComponent(txfMajor_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jfEditMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeEdit)
                    .addComponent(btnUpdate_EditMember))
                .addGap(48, 48, 48))
        );

        jfRemoveMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfRemoveMember.setTitle("Remove Member");
        jfRemoveMember.setLocation(new java.awt.Point(600, 300));

        jLabel1.setText("Id:");

        jLabel2.setText("Name:");

        removeBtn.setBackground(new java.awt.Color(51, 153, 255));
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Find and Remove");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        closeRemove.setBackground(new java.awt.Color(51, 102, 255));
        closeRemove.setForeground(new java.awt.Color(255, 255, 255));
        closeRemove.setText("Cancel");
        closeRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jfRemoveMemberLayout = new javax.swing.GroupLayout(jfRemoveMember.getContentPane());
        jfRemoveMember.getContentPane().setLayout(jfRemoveMemberLayout);
        jfRemoveMemberLayout.setHorizontalGroup(
            jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfRemoveMemberLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfRemoveMemberLayout.createSequentialGroup()
                        .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeID)
                            .addComponent(removeName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jfRemoveMemberLayout.createSequentialGroup()
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(closeRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jfRemoveMemberLayout.setVerticalGroup(
            jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfRemoveMemberLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(removeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(removeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jfRemoveMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(closeRemove))
                .addGap(36, 36, 36))
        );

        jfRemoveSelectedMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Are you sure you want to delete this member?");

        sure.setText("YES");
        sure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sureMouseClicked(evt);
            }
        });

        notsure.setText("NO");
        notsure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notsureMouseClicked(evt);
            }
        });

        another.setBackground(new java.awt.Color(0, 153, 204));
        another.setForeground(new java.awt.Color(255, 255, 255));
        another.setText("Delete another member");
        another.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anotherMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jfRemoveSelectedMemberLayout = new javax.swing.GroupLayout(jfRemoveSelectedMember.getContentPane());
        jfRemoveSelectedMember.getContentPane().setLayout(jfRemoveSelectedMemberLayout);
        jfRemoveSelectedMemberLayout.setHorizontalGroup(
            jfRemoveSelectedMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfRemoveSelectedMemberLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jfRemoveSelectedMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jfRemoveSelectedMemberLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(jfRemoveSelectedMemberLayout.createSequentialGroup()
                        .addGroup(jfRemoveSelectedMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jfRemoveSelectedMemberLayout.createSequentialGroup()
                                .addComponent(sure)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notsure))
                            .addComponent(another, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))))
        );
        jfRemoveSelectedMemberLayout.setVerticalGroup(
            jfRemoveSelectedMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfRemoveSelectedMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfRemoveSelectedMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sure)
                    .addComponent(notsure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(another)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jfSearchMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filter");
        jLabel9.setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel10.setText("Name:");

        jLabel11.setText("ID:");

        jLabel12.setText("Position:");

        jLabel13.setText("Team:");

        searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameActionPerformed(evt);
            }
        });

        findbtn.setBackground(new java.awt.Color(0, 153, 204));
        findbtn.setForeground(new java.awt.Color(255, 255, 255));
        findbtn.setText("Find");
        findbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbtnMouseClicked(evt);
            }
        });
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });

        closeSearch.setBackground(new java.awt.Color(0, 153, 204));
        closeSearch.setForeground(new java.awt.Color(255, 255, 255));
        closeSearch.setText("Cancel");
        closeSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSearchMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Enter at least one information ");
        jLabel15.setToolTipText("");

        javax.swing.GroupLayout jfSearchMemberLayout = new javax.swing.GroupLayout(jfSearchMember.getContentPane());
        jfSearchMember.getContentPane().setLayout(jfSearchMemberLayout);
        jfSearchMemberLayout.setHorizontalGroup(
            jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchMemberLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSearchMemberLayout.createSequentialGroup()
                        .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchName)
                            .addComponent(searchID)
                            .addComponent(searchPos, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(searchTeam)))
                    .addGroup(jfSearchMemberLayout.createSequentialGroup()
                        .addComponent(findbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfSearchMemberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jfSearchMemberLayout.createSequentialGroup()
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSearchMemberLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfSearchMemberLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfSearchMemberLayout.setVerticalGroup(
            jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(19, 19, 19)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(searchPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jfSearchMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findbtn)
                    .addComponent(closeSearch))
                .addGap(33, 33, 33))
        );

        jfSearchResult.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfSearchResult.setLocation(new java.awt.Point(500, 200));

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.1", "Name", "ID", "Position", "Team"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfSearchResultLayout = new javax.swing.GroupLayout(jfSearchResult.getContentPane());
        jfSearchResult.getContentPane().setLayout(jfSearchResultLayout);
        jfSearchResultLayout.setHorizontalGroup(
            jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jfSearchResultLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jButton1))
        );
        jfSearchResultLayout.setVerticalGroup(
            jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchResultLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jpnMember.setBackground(new java.awt.Color(238, 238, 238));

        btnAddMember.setBackground(new java.awt.Color(61, 90, 128));
        btnAddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/person_add_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnAddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMemberMouseClicked(evt);
            }
        });

        btnDeleteMember.setBackground(new java.awt.Color(61, 90, 128));
        btnDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/person_remove_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnDeleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMemberMouseClicked(evt);
            }
        });

        btnEditMember.setBackground(new java.awt.Color(61, 90, 128));
        btnEditMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/edit_note_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnEditMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMemberMouseClicked(evt);
            }
        });

        jpnMemberTitle.setBackground(new java.awt.Color(61, 90, 128));
        jpnMemberTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 50, 65), 4));

        lbMemberTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMemberTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbMemberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMemberTitle.setText("Member list");

        javax.swing.GroupLayout jpnMemberTitleLayout = new javax.swing.GroupLayout(jpnMemberTitle);
        jpnMemberTitle.setLayout(jpnMemberTitleLayout);
        jpnMemberTitleLayout.setHorizontalGroup(
            jpnMemberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnMemberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbMemberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE))
        );
        jpnMemberTitleLayout.setVerticalGroup(
            jpnMemberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jpnMemberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMemberTitleLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMemberTitle)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnFilterMember.setBackground(new java.awt.Color(61, 90, 128));
        btnFilterMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/4781833_filter_filters_funnel_list_navigation_icon (2).png"))); // NOI18N
        btnFilterMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilterMemberMouseClicked(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Personal ID", "Positon", "Team"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srpMember.setViewportView(tblMember);
        if (tblMember.getColumnModel().getColumnCount() > 0) {
            tblMember.getColumnModel().getColumn(0).setResizable(false);
            tblMember.getColumnModel().getColumn(1).setResizable(false);
            tblMember.getColumnModel().getColumn(2).setResizable(false);
            tblMember.getColumnModel().getColumn(3).setResizable(false);
            tblMember.getColumnModel().getColumn(4).setResizable(false);
        }

        btnDetailsMember.setBackground(new java.awt.Color(61, 90, 128));
        btnDetailsMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_management/image/quick_reference_all_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnDetailsMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailsMemberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnMemberLayout = new javax.swing.GroupLayout(jpnMember);
        jpnMember.setLayout(jpnMemberLayout);
        jpnMemberLayout.setHorizontalGroup(
            jpnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMemberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(srpMember, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(jpnMemberLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnAddMember)
                .addGap(74, 74, 74)
                .addComponent(btnDeleteMember)
                .addGap(70, 70, 70)
                .addComponent(btnEditMember)
                .addGap(74, 74, 74)
                .addComponent(btnDetailsMember)
                .addGap(67, 67, 67)
                .addComponent(btnFilterMember)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMemberLayout.setVerticalGroup(
            jpnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMemberLayout.createSequentialGroup()
                .addComponent(jpnMemberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(srpMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jpnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddMember)
                    .addComponent(btnDeleteMember)
                    .addComponent(btnEditMember)
                    .addComponent(btnFilterMember)
                    .addComponent(btnDetailsMember))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMouseClicked
        // TODO add your handling code here:
        jfAddMember.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnAddMemberMouseClicked

    private void btnDeleteMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMemberMouseClicked

        int selectedRow = tblMember.getSelectedRow();
        int remove_id = (int) tblMember.getModel().getValueAt(selectedRow,0);
        if(selectedRow == -1) JOptionPane.showMessageDialog(btnAdd_AddMember, "Please select row to delete");
        // Nếu có hàng được chọn, hiển thị hộp thoại xác nhận trước khi xóa hàng
        if (selectedRow != -1) {
            int confirmed = JOptionPane.showConfirmDialog(null, 
                "Are you sure you want to delete this row?", 
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                model.removeRow(selectedRow);
                controller.removeMemberById(remove_id);
            }
        }   
    }//GEN-LAST:event_btnDeleteMemberMouseClicked

    private void btnEditMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMemberMouseClicked
        selectedIndex = tblMember.getSelectedRow();
        int edit_id = 0;
        if (controller.isEmpty()){
            JOptionPane.showMessageDialog(btnAdd_AddMember, "There is nothing to edit");
        }
        else if (selectedIndex == -1){
            JOptionPane.showMessageDialog(btnAdd_AddMember, "Select row to edit");
        }
        else {
            edit_id = (int) tblMember.getModel().getValueAt(selectedIndex,0);
            Member t = controller.getMemberById(edit_id);
            txfName_EditMember.setText(t.getName());    
            txfPersonalId_EditMember.setText(t.getName());  
            try {
                dcDateOfBirth_EditMember.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(t.getDate_of_birth()));
            }
            catch (Exception e) {
                System.out.println(e);
            }
            cbGender_EditMember.setSelectedIndex((t.getGender()== Member.Gender.MALE) ? 0 : 1);   
            txfMajor_EditMember.setText(t.getMajor()); 
            cbPosition_EditMember.setSelectedIndex((t.getPosition()== Member.Position.MEMBER) ? 0 : 1);   
            txfEmail_EditMember.setText(t.getEmail()); 
            jfEditMember.setVisible(true);
        }
    }//GEN-LAST:event_btnEditMemberMouseClicked
    
    private void btnFilterMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilterMemberMouseClicked
        // TODO add your handling code here:
        //search Search = new search(listener);
        //Search.setListener(this);
        jfSearchMember.setVisible(true);
    }//GEN-LAST:event_btnFilterMemberMouseClicked

    private void btnDetailsMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMemberMouseClicked
        // TODO add your handling code here:
        int row= tblMember.getSelectedRow();
        if(row<0) {JOptionPane.showMessageDialog(this,"Please select a member");}
        else
        {
            int id=(int) tblMember.getModel().getValueAt(selectedIndex,0);
        Member selectedMember=controller.getMemberById(id);
        String message = "ID: " + selectedMember.getId() + "\n"
               + "Name: " + selectedMember.getName() + "\n"
               + "Position: " + selectedMember.getPosition() + "\n"
               + "Team: " + selectedMember.getTeam_id() + "\n"
               + "date of birth: " + selectedMember.getDate_of_birth() + "\n"
               + "Email: " + selectedMember.getEmail() + "\n"
               + "Gender: " + selectedMember.getGender() + "\n"
               + "Major: " + selectedMember.getMajor();

JOptionPane.showMessageDialog(null, message, "Member Information", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_btnDetailsMemberMouseClicked

    private void txfName_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName_AddMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName_AddMemberActionPerformed

    private void txfPersonalId_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPersonalId_AddMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPersonalId_AddMemberActionPerformed

    private void btnAdd_AddMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_AddMemberMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Member t = new Member();

        t.setName(txfName_AddMember.getText());
        t.setPersonal_id(txfPersonalId_AddMember.getText());
        t.setDate_of_birth(new SimpleDateFormat("yyyy-MM-dd").format(dcDateOfBirth_AddMember.getDate()));
        t.setGender((cbGender_AddMember.getSelectedIndex() == 0) ? Member.Gender.MALE : Member.Gender.FEMALE);
        t.setMajor(txfMajor_EditMember.getText());
        t.setPosition((cbPosition_AddMember.getSelectedIndex() == 0) ? Member.Position.MEMBER : Member.Position.LEADER);
        t.setEmail(txfEmail_AddMember.getText());
            
         // TODO add your handling code here:
        System.out.println(t.getGender());
        int n = controller.appendMember(t);
        
        txfName_AddMember.setText("");    
        txfPersonalId_AddMember.setText("");   
        //dcDateOfBirth_EditMember.setDate(new java.util.Date());
        cbGender_AddMember.setSelectedIndex(0);   
        txfMajor_AddMember.setText(""); 
        cbPosition_AddMember.setSelectedIndex(0);   
        txfEmail_AddMember.setText(""); 
        jfEditMember.setVisible(false);
        
        model.addRow(new Object[]{
            n, t.getName(), t.getPersonal_id(), t.getPosition(), t.getTeam_id()
        });
    }//GEN-LAST:event_btnAdd_AddMemberMouseClicked

    private void btnCancel_AddMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancel_AddMemberMouseClicked
        // TODO add your handling code here:
        jfAddMember.setVisible(false);
    }//GEN-LAST:event_btnCancel_AddMemberMouseClicked

    private void btnCancel_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_AddMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel_AddMemberActionPerformed

    private void btnNewTeam_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTeam_AddMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewTeam_AddMemberActionPerformed

    private void cbPosition_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPosition_AddMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPosition_AddMemberActionPerformed

    private void closeEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeEditMouseClicked
        // TODO add your handling code here:
        jfEditMember.setVisible(false);
    }//GEN-LAST:event_closeEditMouseClicked

    private void closeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeEditActionPerformed

    private void jfEditMemberformWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfEditMemberformWindowOpened
     // TODO add your handling code here:
    }//GEN-LAST:event_jfEditMemberformWindowOpened

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
        jfRemoveMember.setVisible(false);
        String name = removeName.getText();
        String id = removeID.getText();
        if(id.equals("")||name.equals(""))
        {JOptionPane.showMessageDialog(this,"You are required to input");}
        //listener.onRemove(id,name);
    }//GEN-LAST:event_removeBtnMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed

    private void closeRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeRemoveMouseClicked
        // TODO add your handling code here:
        jfRemoveMember.setVisible(false);
    }//GEN-LAST:event_closeRemoveMouseClicked

    private void sureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sureMouseClicked
        // TODO add your handling code here:
        jfRemoveSelectedMember.setVisible(false);
        //listener.onRemove2();
    }//GEN-LAST:event_sureMouseClicked

    private void notsureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notsureMouseClicked
        // TODO add your handling code here:
        //dispose();

    }//GEN-LAST:event_notsureMouseClicked

    private void anotherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotherMouseClicked
        // TODO add your handling code here:
        /*dispose();
        remove rm = new remove(listener);
        rm.setListener(listener);
        rm.setVisible(true);*/
    }//GEN-LAST:event_anotherMouseClicked

    private void searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchNameActionPerformed

    private void findbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbtnMouseClicked
        // TODO add your handling code here:
        jfSearchMember.setVisible(false);
        String name = searchName.getText();
        String id = searchID.getText();
        String pos = searchPos.getText();
        String team = searchTeam.getText();
        //listener.onSearch(name,id,pos,team);
    }//GEN-LAST:event_findbtnMouseClicked

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findbtnActionPerformed

    private void closeSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSearchMouseClicked
        // TODO add your handling code here:
        jfSearchMember.setVisible(false);
    }//GEN-LAST:event_closeSearchMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jfSearchMember.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfName_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName_EditMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName_EditMemberActionPerformed

    private void txfPersonalId_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPersonalId_EditMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPersonalId_EditMemberActionPerformed

    private void cbPosition_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPosition_EditMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPosition_EditMemberActionPerformed

    private void btnNewTeam_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTeam_EditMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewTeam_EditMemberActionPerformed

    private void btnUpdate_EditMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_EditMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate_EditMemberMouseClicked

    private void btnUpdate_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_EditMemberActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, 
                    "Are you sure you want to edit this row?", 
                    "Confirm Edit", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION){
            Member t = new Member();
            int edit_id = (int) tblMember.getModel().getValueAt(selectedIndex,0);
            t.setId(edit_id);
            t.setName(txfName_EditMember.getText());
            t.setPersonal_id(txfPersonalId_EditMember.getText());
            t.setDate_of_birth(new SimpleDateFormat("yyyy-MM-dd").format(dcDateOfBirth_EditMember.getDate()));
            t.setGender((cbGender_EditMember.getSelectedIndex() == 0) ? Member.Gender.MALE : Member.Gender.FEMALE);
            t.setMajor(txfMajor_EditMember.getText());
            t.setPosition((cbPosition_EditMember.getSelectedIndex() == 0) ? Member.Position.MEMBER : Member.Position.LEADER);
            t.setEmail(txfEmail_EditMember.getText());
            
            txfName_EditMember.setText("");    
            txfPersonalId_EditMember.setText("");   
            //dcDateOfBirth_EditMember.setDate(new java.util.Date());
            cbGender_EditMember.setSelectedIndex(0);   
            txfMajor_EditMember.setText(""); 
            cbPosition_EditMember.setSelectedIndex(0);   
            txfEmail_EditMember.setText(""); 
            jfEditMember.setVisible(false);
            
            model.setValueAt((Object)edit_id,selectedIndex,0);
            model.setValueAt(t.getName(),selectedIndex,1);
            model.setValueAt(t.getPersonal_id(),selectedIndex,2);
            model.setValueAt(t.getPosition() == Member.Position.MEMBER ? "MEMBER" : "LEADER",selectedIndex,3);
            model.setValueAt(t.getTeam_id(),selectedIndex,4);
            
            controller.editMember(t);
        }
    }//GEN-LAST:event_btnUpdate_EditMemberActionPerformed

    private void member_add_buttonMouseClicked(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Object addmember() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void showlist() {
    // Tạo đối tượng DefaultTableModel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No.");
    model.addColumn("Name");
    model.addColumn("Personal ID");
    model.addColumn("Position");
    model.addColumn("Team");
    
    // Thêm các phần tử trong danh sách memberList vào model
    int i = 1;
    for (int j = 0; j < memberList.getSize(); j++) {
        Member member = memberList.getMember(j);
        model.addRow(new Object[]{i, member.getName(), member.getId(), member.getPosition(), member.getTeam_id()});
        i++;
    }
    this.tblMember.setModel(model);
}

    /*@Override
    public void searchTable(List<Member> a) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/

    private Container getContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class AddMember {

        public AddMember() {
        }
    }

    /**
     * @param args the command line arguments
     */

    public class MemberList {
    private List<Member> memberList;
    public int count;
    public MemberList() {
        memberList = new ArrayList<>();
        count = 0;
    }
    
    public void addMember(Member member) {
        memberList.add(member);
        count++;
    }
    
    public void removeMember(int index) {
        memberList.remove(index);
        count--;
    }
   public boolean removeMember(int id, String name) {
    for (Member member : memberList) {
        if (member.getId() == id && member.getName().equals(name)) {
            memberList.remove(member);
            count--;
            return true;
        }
    }
    return false;
}
    public Member getMember(int index) {
        return memberList.get(index);
    }
    
    public int getSize() {
        return memberList.size();
    }
    public List<Member> getMemberList() {
    return memberList;
}
    public List<Member> ListSearch(String name, String id, String pos, String team) {
    List<Member> searchResult = new ArrayList<>();
    for (Member member : memberList) {
        if ((name.isEmpty() || member.getName().equals(name))
                && (id.isEmpty() || member.getId() == Integer.parseInt(id))
                && (pos.isEmpty() || member.getPosition().equals(pos))
                && (team.isEmpty() || member.getTeam_id() == Integer.parseInt(team))) {
            searchResult.add(member);
        }
    }
    return searchResult;
}
    public Member detail(int id)
    {
        for(Member member :memberList)
        {
            if(member.getId() == id)
                return member;
        }
        return null;
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton another;
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnAdd_AddMember;
    private javax.swing.JButton btnCancel_AddMember;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDetailsMember;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JButton btnFilterMember;
    private javax.swing.JButton btnNewTeam_AddMember;
    private javax.swing.JButton btnNewTeam_EditMember;
    private javax.swing.JButton btnUpdate_EditMember;
    private javax.swing.JComboBox<String> cbGender_AddMember;
    private javax.swing.JComboBox<String> cbGender_EditMember;
    private javax.swing.JComboBox<String> cbPosition_AddMember;
    private javax.swing.JComboBox<String> cbPosition_EditMember;
    private javax.swing.JComboBox<String> cbTeam_AddMember;
    private javax.swing.JComboBox<String> cbTeam_EditMember;
    private javax.swing.JButton closeEdit;
    private javax.swing.JButton closeRemove;
    private javax.swing.JButton closeSearch;
    private com.toedter.calendar.JDateChooser dcDateOfBirth_AddMember;
    private com.toedter.calendar.JDateChooser dcDateOfBirth_EditMember;
    private javax.swing.JButton findbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame jfAddMember;
    private javax.swing.JFrame jfEditMember;
    private javax.swing.JFrame jfRemoveMember;
    private javax.swing.JFrame jfRemoveSelectedMember;
    private javax.swing.JFrame jfSearchMember;
    private javax.swing.JFrame jfSearchResult;
    private javax.swing.JPanel jpnMember;
    private javax.swing.JPanel jpnMemberTitle;
    private javax.swing.JLabel lbDateOfBirth_AddMember;
    private javax.swing.JLabel lbDateOfBirth_EditMember;
    private javax.swing.JLabel lbEmail_AddMember;
    private javax.swing.JLabel lbEmail_EditMember;
    private javax.swing.JLabel lbGender_AddMember;
    private javax.swing.JLabel lbGender_EditMember;
    private javax.swing.JLabel lbMajor_AddMember;
    private javax.swing.JLabel lbMajor_EditMember;
    private javax.swing.JLabel lbMemberTitle;
    private javax.swing.JLabel lbName_AddMember;
    private javax.swing.JLabel lbName_EditMember;
    private javax.swing.JLabel lbPersonalId_AddMember;
    private javax.swing.JLabel lbPersonalId_EditMember;
    private javax.swing.JLabel lbPosition_AddMember;
    private javax.swing.JLabel lbPosition_EditMember;
    private javax.swing.JLabel lbTeam_AddMember;
    private javax.swing.JLabel lbTeam_EditMember;
    private javax.swing.JButton notsure;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTextField removeID;
    private javax.swing.JTextField removeName;
    private javax.swing.JTextField searchID;
    private javax.swing.JTextField searchName;
    private javax.swing.JTextField searchPos;
    private javax.swing.JTable searchTable;
    private javax.swing.JTextField searchTeam;
    private javax.swing.JScrollPane srpMember;
    private javax.swing.JButton sure;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txfEmail_AddMember;
    private javax.swing.JTextField txfEmail_EditMember;
    private javax.swing.JTextField txfMajor_AddMember;
    private javax.swing.JTextField txfMajor_EditMember;
    private javax.swing.JTextField txfName_AddMember;
    private javax.swing.JTextField txfName_EditMember;
    private javax.swing.JTextField txfPersonalId_AddMember;
    private javax.swing.JTextField txfPersonalId_EditMember;
    // End of variables declaration//GEN-END:variables
}
